/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type TestId = bigint;
export type QuestionId = bigint;
export interface Port {
    id: PortId;
    protocol: string;
    service: string;
    description: string;
    portNumber: bigint;
}
export interface Domain {
    domainId: DomainId;
    domainName: string;
    certificationId: CertificationId;
    subdomains: Array<string>;
    description: string;
}
export type CertificationId = string;
export interface TestResult {
    certificationId: CertificationId;
    score: bigint;
    totalQuestions: bigint;
    timestamp: Time;
    testId: TestId;
}
export type KeyTermId = bigint;
export type ProtocolId = bigint;
export type ObjectiveId = bigint;
export type FlashcardId = bigint;
export type DomainId = bigint;
export interface Flashcard {
    id: FlashcardId;
    front: string;
    timesIncorrect: bigint;
    back: string;
    timesCorrect: bigint;
}
export type PortId = bigint;
export interface Question {
    id: QuestionId;
    domain: string;
    certificationId: CertificationId;
    correctAnswer: string;
    questionText: string;
}
export interface Objective {
    domainId: DomainId;
    difficulty: bigint;
    description: string;
    objectiveId: ObjectiveId;
}
export interface Protocol {
    id: ProtocolId;
    name: string;
    port?: bigint;
    description: string;
}
export interface KeyTerm {
    id: KeyTermId;
    term: string;
    definition: string;
}
export interface backendInterface {
    addDomain(certName: string, name: string, description: string, subdomains: Array<string>): Promise<DomainId>;
    addFlashcard(certificationId: CertificationId, front: string, back: string): Promise<void>;
    addKeyTerm(term: string, definition: string): Promise<KeyTermId>;
    addObjective(domainId: DomainId, description: string, difficulty: bigint): Promise<ObjectiveId>;
    addPort(portNumber: bigint, protocol: string, service: string, description: string): Promise<PortId>;
    addProtocol(name: string, description: string, port: bigint | null): Promise<ProtocolId>;
    addQuestion(certificationId: CertificationId, domain: string, questionText: string, correctAnswer: string): Promise<QuestionId>;
    getCertifications(): Promise<Array<string>>;
    getDomains(certificationId: CertificationId): Promise<Array<Domain>>;
    getFlashcards(certificationId: CertificationId): Promise<Array<Flashcard>>;
    getKeyTerms(): Promise<Array<KeyTerm>>;
    getObjectives(domainId: DomainId): Promise<Array<Objective>>;
    getPorts(): Promise<Array<Port>>;
    getProtocols(): Promise<Array<Protocol>>;
    getQuestionsForCertification(certificationId: CertificationId): Promise<Array<Question>>;
    getTestResultsForCertification(certificationId: CertificationId): Promise<Array<TestResult>>;
    submitTestResult(certificationId: CertificationId, score: bigint, totalQuestions: bigint): Promise<TestId>;
}
import type { Protocol as _Protocol, ProtocolId as _ProtocolId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addDomain(arg0: string, arg1: string, arg2: string, arg3: Array<string>): Promise<DomainId> {
        if (this.processError) {
            try {
                const result = await this.actor.addDomain(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDomain(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addFlashcard(arg0: CertificationId, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFlashcard(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFlashcard(arg0, arg1, arg2);
            return result;
        }
    }
    async addKeyTerm(arg0: string, arg1: string): Promise<KeyTermId> {
        if (this.processError) {
            try {
                const result = await this.actor.addKeyTerm(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addKeyTerm(arg0, arg1);
            return result;
        }
    }
    async addObjective(arg0: DomainId, arg1: string, arg2: bigint): Promise<ObjectiveId> {
        if (this.processError) {
            try {
                const result = await this.actor.addObjective(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addObjective(arg0, arg1, arg2);
            return result;
        }
    }
    async addPort(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<PortId> {
        if (this.processError) {
            try {
                const result = await this.actor.addPort(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPort(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addProtocol(arg0: string, arg1: string, arg2: bigint | null): Promise<ProtocolId> {
        if (this.processError) {
            try {
                const result = await this.actor.addProtocol(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProtocol(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addQuestion(arg0: CertificationId, arg1: string, arg2: string, arg3: string): Promise<QuestionId> {
        if (this.processError) {
            try {
                const result = await this.actor.addQuestion(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQuestion(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async getCertifications(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCertifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCertifications();
            return result;
        }
    }
    async getDomains(arg0: CertificationId): Promise<Array<Domain>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDomains(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDomains(arg0);
            return result;
        }
    }
    async getFlashcards(arg0: CertificationId): Promise<Array<Flashcard>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlashcards(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlashcards(arg0);
            return result;
        }
    }
    async getKeyTerms(): Promise<Array<KeyTerm>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKeyTerms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKeyTerms();
            return result;
        }
    }
    async getObjectives(arg0: DomainId): Promise<Array<Objective>> {
        if (this.processError) {
            try {
                const result = await this.actor.getObjectives(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getObjectives(arg0);
            return result;
        }
    }
    async getPorts(): Promise<Array<Port>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPorts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPorts();
            return result;
        }
    }
    async getProtocols(): Promise<Array<Protocol>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProtocols();
                return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProtocols();
            return from_candid_vec_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuestionsForCertification(arg0: CertificationId): Promise<Array<Question>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuestionsForCertification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuestionsForCertification(arg0);
            return result;
        }
    }
    async getTestResultsForCertification(arg0: CertificationId): Promise<Array<TestResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestResultsForCertification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestResultsForCertification(arg0);
            return result;
        }
    }
    async submitTestResult(arg0: CertificationId, arg1: bigint, arg2: bigint): Promise<TestId> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTestResult(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTestResult(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_Protocol_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Protocol): Protocol {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProtocolId;
    name: string;
    port: [] | [bigint];
    description: string;
}): {
    id: ProtocolId;
    name: string;
    port?: bigint;
    description: string;
} {
    return {
        id: value.id,
        name: value.name,
        port: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.port)),
        description: value.description
    };
}
function from_candid_vec_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Protocol>): Array<Protocol> {
    return value.map((x)=>from_candid_Protocol_n3(_uploadFile, _downloadFile, x));
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
