/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DomainId = IDL.Nat;
export const CertificationId = IDL.Text;
export const KeyTermId = IDL.Nat;
export const ObjectiveId = IDL.Nat;
export const PortId = IDL.Nat;
export const ProtocolId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const Domain = IDL.Record({
  'domainId' : DomainId,
  'domainName' : IDL.Text,
  'certificationId' : CertificationId,
  'subdomains' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const FlashcardId = IDL.Nat;
export const Flashcard = IDL.Record({
  'id' : FlashcardId,
  'front' : IDL.Text,
  'timesIncorrect' : IDL.Nat,
  'back' : IDL.Text,
  'timesCorrect' : IDL.Nat,
});
export const KeyTerm = IDL.Record({
  'id' : KeyTermId,
  'term' : IDL.Text,
  'definition' : IDL.Text,
});
export const Objective = IDL.Record({
  'domainId' : DomainId,
  'difficulty' : IDL.Nat,
  'description' : IDL.Text,
  'objectiveId' : ObjectiveId,
});
export const Port = IDL.Record({
  'id' : PortId,
  'protocol' : IDL.Text,
  'service' : IDL.Text,
  'description' : IDL.Text,
  'portNumber' : IDL.Nat,
});
export const Protocol = IDL.Record({
  'id' : ProtocolId,
  'name' : IDL.Text,
  'port' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'domain' : IDL.Text,
  'certificationId' : CertificationId,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
});
export const Time = IDL.Int;
export const TestId = IDL.Nat;
export const TestResult = IDL.Record({
  'certificationId' : CertificationId,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'testId' : TestId,
});

export const idlService = IDL.Service({
  'addDomain' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [DomainId],
      [],
    ),
  'addFlashcard' : IDL.Func([CertificationId, IDL.Text, IDL.Text], [], []),
  'addKeyTerm' : IDL.Func([IDL.Text, IDL.Text], [KeyTermId], []),
  'addObjective' : IDL.Func([DomainId, IDL.Text, IDL.Nat], [ObjectiveId], []),
  'addPort' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PortId], []),
  'addProtocol' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [ProtocolId],
      [],
    ),
  'addQuestion' : IDL.Func(
      [CertificationId, IDL.Text, IDL.Text, IDL.Text],
      [QuestionId],
      [],
    ),
  'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDomains' : IDL.Func([CertificationId], [IDL.Vec(Domain)], ['query']),
  'getFlashcards' : IDL.Func(
      [CertificationId],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getKeyTerms' : IDL.Func([], [IDL.Vec(KeyTerm)], ['query']),
  'getObjectives' : IDL.Func([DomainId], [IDL.Vec(Objective)], ['query']),
  'getPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
  'getProtocols' : IDL.Func([], [IDL.Vec(Protocol)], ['query']),
  'getQuestionsForCertification' : IDL.Func(
      [CertificationId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getTestResultsForCertification' : IDL.Func(
      [CertificationId],
      [IDL.Vec(TestResult)],
      ['query'],
    ),
  'submitTestResult' : IDL.Func(
      [CertificationId, IDL.Nat, IDL.Nat],
      [TestId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DomainId = IDL.Nat;
  const CertificationId = IDL.Text;
  const KeyTermId = IDL.Nat;
  const ObjectiveId = IDL.Nat;
  const PortId = IDL.Nat;
  const ProtocolId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const Domain = IDL.Record({
    'domainId' : DomainId,
    'domainName' : IDL.Text,
    'certificationId' : CertificationId,
    'subdomains' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const FlashcardId = IDL.Nat;
  const Flashcard = IDL.Record({
    'id' : FlashcardId,
    'front' : IDL.Text,
    'timesIncorrect' : IDL.Nat,
    'back' : IDL.Text,
    'timesCorrect' : IDL.Nat,
  });
  const KeyTerm = IDL.Record({
    'id' : KeyTermId,
    'term' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Objective = IDL.Record({
    'domainId' : DomainId,
    'difficulty' : IDL.Nat,
    'description' : IDL.Text,
    'objectiveId' : ObjectiveId,
  });
  const Port = IDL.Record({
    'id' : PortId,
    'protocol' : IDL.Text,
    'service' : IDL.Text,
    'description' : IDL.Text,
    'portNumber' : IDL.Nat,
  });
  const Protocol = IDL.Record({
    'id' : ProtocolId,
    'name' : IDL.Text,
    'port' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'domain' : IDL.Text,
    'certificationId' : CertificationId,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
  });
  const Time = IDL.Int;
  const TestId = IDL.Nat;
  const TestResult = IDL.Record({
    'certificationId' : CertificationId,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'testId' : TestId,
  });
  
  return IDL.Service({
    'addDomain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [DomainId],
        [],
      ),
    'addFlashcard' : IDL.Func([CertificationId, IDL.Text, IDL.Text], [], []),
    'addKeyTerm' : IDL.Func([IDL.Text, IDL.Text], [KeyTermId], []),
    'addObjective' : IDL.Func([DomainId, IDL.Text, IDL.Nat], [ObjectiveId], []),
    'addPort' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PortId], []),
    'addProtocol' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [ProtocolId],
        [],
      ),
    'addQuestion' : IDL.Func(
        [CertificationId, IDL.Text, IDL.Text, IDL.Text],
        [QuestionId],
        [],
      ),
    'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDomains' : IDL.Func([CertificationId], [IDL.Vec(Domain)], ['query']),
    'getFlashcards' : IDL.Func(
        [CertificationId],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getKeyTerms' : IDL.Func([], [IDL.Vec(KeyTerm)], ['query']),
    'getObjectives' : IDL.Func([DomainId], [IDL.Vec(Objective)], ['query']),
    'getPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
    'getProtocols' : IDL.Func([], [IDL.Vec(Protocol)], ['query']),
    'getQuestionsForCertification' : IDL.Func(
        [CertificationId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getTestResultsForCertification' : IDL.Func(
        [CertificationId],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'submitTestResult' : IDL.Func(
        [CertificationId, IDL.Nat, IDL.Nat],
        [TestId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };