/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type CertificationId = string;
export interface Domain {
  'domainId' : DomainId,
  'domainName' : string,
  'certificationId' : CertificationId,
  'subdomains' : Array<string>,
  'description' : string,
}
export type DomainId = bigint;
export interface Flashcard {
  'id' : FlashcardId,
  'front' : string,
  'timesIncorrect' : bigint,
  'back' : string,
  'timesCorrect' : bigint,
}
export type FlashcardId = bigint;
export interface KeyTerm {
  'id' : KeyTermId,
  'term' : string,
  'definition' : string,
}
export type KeyTermId = bigint;
export interface Objective {
  'domainId' : DomainId,
  'difficulty' : bigint,
  'description' : string,
  'objectiveId' : ObjectiveId,
}
export type ObjectiveId = bigint;
export interface PDFProgressRecord {
  'userId' : Principal,
  'certificationId' : CertificationId,
  'percentage' : bigint,
}
export interface Port {
  'id' : PortId,
  'protocol' : string,
  'service' : string,
  'description' : string,
  'portNumber' : bigint,
}
export type PortId = bigint;
export interface Protocol {
  'id' : ProtocolId,
  'name' : string,
  'port' : [] | [bigint],
  'description' : string,
}
export type ProtocolId = bigint;
export interface Question {
  'id' : QuestionId,
  'domain' : string,
  'certificationId' : CertificationId,
  'correctAnswer' : string,
  'questionText' : string,
}
export type QuestionId = bigint;
export type TestId = bigint;
export interface TestResult {
  'certificationId' : CertificationId,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : Time,
  'testId' : TestId,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDomain' : ActorMethod<[string, string, string, Array<string>], DomainId>,
  'addFlashcard' : ActorMethod<[CertificationId, string, string], undefined>,
  'addKeyTerm' : ActorMethod<[string, string], KeyTermId>,
  'addObjective' : ActorMethod<[DomainId, string, bigint], ObjectiveId>,
  'addPort' : ActorMethod<[bigint, string, string, string], PortId>,
  'addProtocol' : ActorMethod<[string, string, [] | [bigint]], ProtocolId>,
  'addQuestion' : ActorMethod<
    [CertificationId, string, string, string],
    QuestionId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPdfProgressRecords' : ActorMethod<[], Array<PDFProgressRecord>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertifications' : ActorMethod<[], Array<string>>,
  'getDomains' : ActorMethod<[CertificationId], Array<Domain>>,
  'getFlashcards' : ActorMethod<[CertificationId], Array<Flashcard>>,
  'getKeyTerms' : ActorMethod<[], Array<KeyTerm>>,
  'getMyPdfProgressRecords' : ActorMethod<[], Array<PDFProgressRecord>>,
  'getObjectives' : ActorMethod<[DomainId], Array<Objective>>,
  'getPorts' : ActorMethod<[], Array<Port>>,
  'getProtocols' : ActorMethod<[], Array<Protocol>>,
  'getQuestionsForCertification' : ActorMethod<
    [CertificationId],
    Array<Question>
  >,
  'getTestResultsForCertification' : ActorMethod<
    [CertificationId],
    Array<TestResult>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOrUpdateProgress' : ActorMethod<[CertificationId, bigint], undefined>,
  'submitTestResult' : ActorMethod<[CertificationId, bigint, bigint], TestId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];