/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DomainId = IDL.Nat;
export const CertificationId = IDL.Text;
export const KeyTermId = IDL.Nat;
export const ObjectiveId = IDL.Nat;
export const PortId = IDL.Nat;
export const ProtocolId = IDL.Nat;
export const QuestionId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PDFProgressRecord = IDL.Record({
  'userId' : IDL.Principal,
  'certificationId' : CertificationId,
  'percentage' : IDL.Nat,
});
export const Time = IDL.Int;
export const TestId = IDL.Nat;
export const TestResult = IDL.Record({
  'certificationId' : CertificationId,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : Time,
  'testId' : TestId,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Domain = IDL.Record({
  'domainId' : DomainId,
  'domainName' : IDL.Text,
  'certificationId' : CertificationId,
  'subdomains' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
});
export const FlashcardId = IDL.Nat;
export const Flashcard = IDL.Record({
  'id' : FlashcardId,
  'front' : IDL.Text,
  'timesIncorrect' : IDL.Nat,
  'back' : IDL.Text,
  'timesCorrect' : IDL.Nat,
});
export const KeyTerm = IDL.Record({
  'id' : KeyTermId,
  'term' : IDL.Text,
  'definition' : IDL.Text,
});
export const Objective = IDL.Record({
  'domainId' : DomainId,
  'difficulty' : IDL.Nat,
  'description' : IDL.Text,
  'objectiveId' : ObjectiveId,
});
export const Port = IDL.Record({
  'id' : PortId,
  'protocol' : IDL.Text,
  'service' : IDL.Text,
  'description' : IDL.Text,
  'portNumber' : IDL.Nat,
});
export const Protocol = IDL.Record({
  'id' : ProtocolId,
  'name' : IDL.Text,
  'port' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
});
export const Question = IDL.Record({
  'id' : QuestionId,
  'domain' : IDL.Text,
  'certificationId' : CertificationId,
  'correctAnswer' : IDL.Text,
  'questionText' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDomain' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [DomainId],
      [],
    ),
  'addFlashcard' : IDL.Func([CertificationId, IDL.Text, IDL.Text], [], []),
  'addKeyTerm' : IDL.Func([IDL.Text, IDL.Text], [KeyTermId], []),
  'addObjective' : IDL.Func([DomainId, IDL.Text, IDL.Nat], [ObjectiveId], []),
  'addPort' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PortId], []),
  'addProtocol' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [ProtocolId],
      [],
    ),
  'addQuestion' : IDL.Func(
      [CertificationId, IDL.Text, IDL.Text, IDL.Text],
      [QuestionId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPdfProgressRecords' : IDL.Func(
      [],
      [IDL.Vec(PDFProgressRecord)],
      ['query'],
    ),
  'getAllTestResultsForCertification' : IDL.Func(
      [CertificationId],
      [IDL.Vec(TestResult)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getDomains' : IDL.Func([CertificationId], [IDL.Vec(Domain)], ['query']),
  'getFlashcards' : IDL.Func(
      [CertificationId],
      [IDL.Vec(Flashcard)],
      ['query'],
    ),
  'getKeyTerms' : IDL.Func([], [IDL.Vec(KeyTerm)], ['query']),
  'getMyPdfProgressRecords' : IDL.Func(
      [],
      [IDL.Vec(PDFProgressRecord)],
      ['query'],
    ),
  'getObjectives' : IDL.Func([DomainId], [IDL.Vec(Objective)], ['query']),
  'getPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
  'getProtocols' : IDL.Func([], [IDL.Vec(Protocol)], ['query']),
  'getQuestionsForCertification' : IDL.Func(
      [CertificationId],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getTestResultsForCertification' : IDL.Func(
      [CertificationId],
      [IDL.Vec(TestResult)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'overwriteTestResults' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveOrUpdateProgress' : IDL.Func([CertificationId, IDL.Nat], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitTestResult' : IDL.Func(
      [CertificationId, IDL.Nat, IDL.Nat],
      [TestId],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DomainId = IDL.Nat;
  const CertificationId = IDL.Text;
  const KeyTermId = IDL.Nat;
  const ObjectiveId = IDL.Nat;
  const PortId = IDL.Nat;
  const ProtocolId = IDL.Nat;
  const QuestionId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PDFProgressRecord = IDL.Record({
    'userId' : IDL.Principal,
    'certificationId' : CertificationId,
    'percentage' : IDL.Nat,
  });
  const Time = IDL.Int;
  const TestId = IDL.Nat;
  const TestResult = IDL.Record({
    'certificationId' : CertificationId,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : Time,
    'testId' : TestId,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Domain = IDL.Record({
    'domainId' : DomainId,
    'domainName' : IDL.Text,
    'certificationId' : CertificationId,
    'subdomains' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
  });
  const FlashcardId = IDL.Nat;
  const Flashcard = IDL.Record({
    'id' : FlashcardId,
    'front' : IDL.Text,
    'timesIncorrect' : IDL.Nat,
    'back' : IDL.Text,
    'timesCorrect' : IDL.Nat,
  });
  const KeyTerm = IDL.Record({
    'id' : KeyTermId,
    'term' : IDL.Text,
    'definition' : IDL.Text,
  });
  const Objective = IDL.Record({
    'domainId' : DomainId,
    'difficulty' : IDL.Nat,
    'description' : IDL.Text,
    'objectiveId' : ObjectiveId,
  });
  const Port = IDL.Record({
    'id' : PortId,
    'protocol' : IDL.Text,
    'service' : IDL.Text,
    'description' : IDL.Text,
    'portNumber' : IDL.Nat,
  });
  const Protocol = IDL.Record({
    'id' : ProtocolId,
    'name' : IDL.Text,
    'port' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
  });
  const Question = IDL.Record({
    'id' : QuestionId,
    'domain' : IDL.Text,
    'certificationId' : CertificationId,
    'correctAnswer' : IDL.Text,
    'questionText' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDomain' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [DomainId],
        [],
      ),
    'addFlashcard' : IDL.Func([CertificationId, IDL.Text, IDL.Text], [], []),
    'addKeyTerm' : IDL.Func([IDL.Text, IDL.Text], [KeyTermId], []),
    'addObjective' : IDL.Func([DomainId, IDL.Text, IDL.Nat], [ObjectiveId], []),
    'addPort' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [PortId], []),
    'addProtocol' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [ProtocolId],
        [],
      ),
    'addQuestion' : IDL.Func(
        [CertificationId, IDL.Text, IDL.Text, IDL.Text],
        [QuestionId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPdfProgressRecords' : IDL.Func(
        [],
        [IDL.Vec(PDFProgressRecord)],
        ['query'],
      ),
    'getAllTestResultsForCertification' : IDL.Func(
        [CertificationId],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCertifications' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getDomains' : IDL.Func([CertificationId], [IDL.Vec(Domain)], ['query']),
    'getFlashcards' : IDL.Func(
        [CertificationId],
        [IDL.Vec(Flashcard)],
        ['query'],
      ),
    'getKeyTerms' : IDL.Func([], [IDL.Vec(KeyTerm)], ['query']),
    'getMyPdfProgressRecords' : IDL.Func(
        [],
        [IDL.Vec(PDFProgressRecord)],
        ['query'],
      ),
    'getObjectives' : IDL.Func([DomainId], [IDL.Vec(Objective)], ['query']),
    'getPorts' : IDL.Func([], [IDL.Vec(Port)], ['query']),
    'getProtocols' : IDL.Func([], [IDL.Vec(Protocol)], ['query']),
    'getQuestionsForCertification' : IDL.Func(
        [CertificationId],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getTestResultsForCertification' : IDL.Func(
        [CertificationId],
        [IDL.Vec(TestResult)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'overwriteTestResults' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveOrUpdateProgress' : IDL.Func([CertificationId, IDL.Nat], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitTestResult' : IDL.Func(
        [CertificationId, IDL.Nat, IDL.Nat],
        [TestId],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };